trigger:
- main

resources:
  repositories:
    - repository: template
      type: git
      name: DevOps

pool:
  vmImage: ubuntu-latest

variables:
  major: '2'
  minor: '1'
  buildConfiguration: 'Release'

extends:
  template: build-nuget-package.yml@template
  parameters:
    solutionToBuild: 'Beis.HelpToGrow.Common.sln'
    projectToPublish: 'Beis.HelpToGrow.Repositories.csproj' # this should include the repositories project/dll as a dependency 